variables:
  DOCKER_BUILDKIT: "1"

image: "mzgroup/dind-awscli-python:2022.11.18-1"

services:
  - docker:dind

stages:
  - QualityCheck
  - Delivery


LintDockerfile:
  stage: QualityCheck
  script:
    - bash ./.scripts/lint-all.sh
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"


BuildAndPush:
  stage: Delivery
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_ACCESS_TOKEN"
    - bash ./.scripts/build-all.sh
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_COMMIT_TAG =~ /\d+.\d+.\d+-?.*$/
