image: "mzgroup/dind-awscli-python:v1.2.0"

services:
  - docker:dind

before_script:
  - pass

stages:
  - QualityCheck
  - Delivery


LintDockerfile:
  stage: QualityCheck
  script:
    - bash ./.scripts/lint-all.sh
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"


BuildAndPush:
  stage: Delivery
  script:
    - bash ./.scripts/build-all.sh
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-?.*$/
