name: Build and push


on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'
  pull_request:
    branches:
      - main


jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - uses: actions/checkout@v2
      - name: Build images and push
        run: bash ./.scripts/build-all.sh
